---

- name: Prep Windows machine with powershell scripts
  include_tasks: 
    file: windows.yml
    apply:
      tags:
        - create-ad
        - join-ad
        - post-ad-join
        - remove-ad
  tags:
  - create-ad
  - join-ad
  - post-ad-join
  - remove-ad

- name: Check AD doesnt have computer object
  include_tasks: 
    file: realmd-checknoexist-ad.yml
    apply:
      tags:
        - create-ad
  tags:
  - create-ad

- name: Create AD computer object
  include_tasks: 
    file: realmd-createcomp-ad.yml
    apply:
      tags:
        - create-ad
  tags:
  - create-ad

- name: Check AD has computer object previously created
  include_tasks: 
    file: realmd-checkexist-ad.yml
    apply:
      tags:
        - join-ad
  tags:
  - join-ad

# - name: AD join
#   include: realmd-join.yml
#   tags: 
#   - join-ad

# - name: Post AD configuration
#   include: realmd-after-join.yml
#   tags: 
#   - post-ad-join
#   - join-ad

- name: Remove existing computer from Active Directory
  include_tasks: 
    file: realmd-remove-existing-ad.yml
    apply:
      tags:
        - remove-ad
  tags:
  - remove-ad

- name: Remove existing computer from Configuration Manager
  include_tasks: 
    file: realmd-remove-existing-configurationmanager.yml
    apply:
      tags:
        - remove-ad
  tags:
  - remove-ad
