---


- name: Remove {{ ad_short_hostname }} from Configuration Manager
  win_shell: |
      powershell.exe -noprofile -executionpolicy bypass -File "C:\csscripts\powershell\sccmdeletecomp.ps1" {{ ad_short_hostname }}
  register: configmanagercomputerobject


- name: Powershell output
  debug:
    var: configmanagercomputerobject

- name: Fail if {{ ad_short_hostname }} was unable to remove in SCCM
  ansible.builtin.debug:
    msg: Debug {{ ad_short_hostname }} SCCM status {{ configmanagercomputerobject.stdout }}
  failed_when: configmanagercomputerobject.stdout is search("Failed")

# The following would require a precheck to confirm that it existed
# - name: Fail if {{ ad_short_hostname }} was not removed from configuration manager
#   ansible.builtin.debug:
#     msg: Debug {{ ad_short_hostname }} AD status {{ configmanagercomputerobject.stdout }}
#   failed_when: configmanagercomputerobject.stdout is not search("removed")
#   when: adcomputerobject.stdout is search("exists")


###############
#- name: Check if {{ ad_short_hostname }} is in SCCM and delete it
#  win_shell: |
#      powershell.exe -noprofile -executionpolicy bypass -File "C:\csscripts\powershell\sccmdeletecomp.ps1" {{ ad_short_hostname }}
#  register: sccmcomputerobject
#
#- name: Powershell output
#  debug:
#    var: sccmcomputerobject
#
#- name: Fail if {{ ad_short_hostname }} was unable to remove in SCCM
#  ansible.builtin.debug:
#    msg: Debug {{ ad_short_hostname }} SCCM status {{ sccmcomputerobject.stdout }}
#  failed_when: sccmcomputerobject.stdout is search("Failed")