---

- name: test powershell should fail
  win_shell: |
      get-host
  register: result_get_host

- name: display result_get_host
  debug:
    var: result_get_host

- name: Check if {{ ad_short_hostname }} is in AD at {{ ad_computer_ou }}
  win_shell: |
      powershell.exe -noprofile -executionpolicy bypass -File "C:\csscripts\powershell\adcheckcomp.ps1" {{ ad_short_hostname }} "{{ ad_computer_ou }}"
  register: adcomputerobject

- name: Powershell output
  debug:
    var: adcomputerobject

- name: Fail if {{ ad_short_hostname }} is in AD at {{ ad_computer_ou }}
  ansible.builtin.debug:
    msg: Debug {{ ad_short_hostname }} AD status {{ adcomputerobject.stdout }} at {{ ad_computer_ou }}
  failed_when: adcomputerobject.stdout is search("exists")
  # failed_when: adcomputerobject.stdout == "exists\n"
