---

- name: Create directory structure
  win_file:
    path: C:\csscripts\powershell
    state: directory

- name: Recursively Copy folder contents to csscripts
  win_copy:
    src: templates/powershell/
    dest: C:\csscripts\powershell
